# AppRole Auth Method
## 1.Enable it
POST http://localhost:8200/v1/sys/auth/approle
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "type": "approle"
}

###

## 2.Set desired set of policies
POST http://localhost:8200/v1/auth/approle/role/my-role
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "policies": "dev-policy, test-policy"
}

###

## 3.Get the role id
GET http://localhost:8200/v1/auth/approle/role/my-role/role-id
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

> {%
    client.global.set("RoleId", response.body.valueOf("data.role_id"));
%}
###

## 4.Create a new secret under the role
POST http://localhost:8200/v1/auth/approle/role/my-role/secret-id
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

> {%
    client.global.set("SecretId", response.body.valueOf("data.secret_id"));
%}
###

## 5.Authenticate
## TODO: Fix it
POST http://localhost:8200/v1/auth/approle/login
Content-Type: application/json

{
  "role_id": {{RoleId}},
  "secret_id": {{SecretId}}
}
###

# Secret engine
## 1.Create a secret using KV version1 named "creds"
POST http://localhost:8200/v1/secret/data/creds
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "data": {"password": "my-long-password"}
}
###

## 2.Get a secret
GET http://localhost:8200/v1/secret/data/creds
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json
###

# UserPass Auth Method
## 1.Enable it
POST http://localhost:8200/v1/sys/auth/userpass
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "type": "userpass"
}
###

## 2.Create / Update user
POST http://localhost:8200/v1/auth/userpass/users/alfredo
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "password": "toledano"
}
###

## 3.Login
POST http://localhost:8200/v1/auth/userpass/login/alfredo
#X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "password": "toledano"
}
###

## 4.Create / Update user, passing policy
POST http://localhost:8200/v1/auth/userpass/users/alfredo
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "password": "toledano",
  "policies": "kv-policy"
}
###

# Policies
## 1.List policies
GET http://localhost:8200/v1/sys/policy
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json
###

## 2.Read policy
GET http://localhost:8200/v1/sys/policy/{{PolicyName}}
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json
###

## 3.Create/Update policy
## Defining the policy via .json file
POST http://localhost:8200/v1/sys/policy/kv-policy
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "policy": "path \"kv/data/automation\" {capabilities = [\"read\"]}"
}
###

# KV
## 1.Enable K/V secrets
POST http://localhost:8200/v1/sys/mounts/apps/artifactory
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "type": "kv",
  "options": {
    "version": "2"
  }
}
###

## 2.Update / Create K/V secrets
POST http://localhost:8200/v1/secret/data/apps/artifactory
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json

{
  "data": {
    "name": "Alfredo"
  }
}
###

## 3.Retrieve K/V secrets
GET http://localhost:8200/v1/secret/data/apps/artifactory
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json
###

# Sys
## 1.List auth methods
GET http://localhost:8200/v1/sys/auth
X-VAULT-TOKEN: {{XVaultToken}}
Content-Type: application/json
###

